// Ajax actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const RETRIEVE_PULL_REQUESTS_DATA_SUCCESS = 'RETRIEVE_MED_ACTIVITIES_DATA_SUCCESS';
export const RETRIEVE_PULL_REQUESTS_DATA_FAILED = 'RETRIEVE_MED_ACTIVITIES_DATA_FAILED';
export const RETRIEVE_PULL_REQUESTS_DATA = 'RETRIEVE_MED_ACTIVITY_DATA';
